#!/usr/bin/env python3
# ============================================================================
# K2GO-394 -- Build the offline maps catalog -> src/main/assets/maps_catalog.csv
#
# One builder for the maps catalog (there is no second one -- this replaces the
# inline refreshMapsSizes Gradle logic). Self-contained: for each whole-world
# pmtiles layer it fetches the <size> from the layer's .meta4 on the maps mirror
# and writes the FINAL CSV directly. Rows are "group,level,file,bytes,date":
#   * file  -- the mirror file name. The APP sends this as the download id; the
#     box (static/dashboard/sockets/maps-base.exec.ts) composes the real URL as
#     MAPS_BASE_URL + file, the same split kiwix uses (app holds the id, the box
#     owns the mirror host). So the switnet host never enters the app.
#   * bytes -- last-known size for the Choose screen's offline estimate
#     (MapsCatalog.sizeMb), the job the old maps_sizes.csv did.
#
# The file names follow roles/maps/defaults/main.yml; update the three data dates
# below when the role bumps them (same contract the inline task had).
#
# Usage:
#   python3 tools/build_maps_catalog.py            # fetch live -> CSV
#
# Gradle runs this on release builds and on demand (./gradlew refreshMapsCatalog);
# the weekly publish-catalogs workflow runs it too and uploads the CSV + manifest
# to Cloudflare, so a later app-side pull can refresh it without an APK release.
# Never fatal: an incomplete fetch keeps the committed CSV (last known).
# ============================================================================
import os, re, sys, urllib.request
from datetime import datetime, timezone

BASE = "https://iiab.switnet.org/maps/2/"
UA = "iiab-android-build"

# Data dates from roles/maps/defaults/main.yml (maps_vector_data_date /
# maps_slow_data_date / maps_search_data_date). Keep in sync with the role.
VECTOR_DATE = "2026-07-01"
SLOW_DATE = "2025-12-10"
SEARCH_DATE = "2026-04-22"

# "group|level" -> mirror file name (whole-world pmtiles; search is a tarball).
# Mirrors the wizard allowlist in MapsRunroleCommand: vector (group "base")
# nat-z8/11/14, satellite 7/9/11/13, terrain 7/8/9/10, plus the search DB.
FILES = {
    "base|nat-z8": f"naturalearth-openmaptiles.{SLOW_DATE}.z00-z08.pmtiles",
    "base|11": f"openstreetmap-openmaptiles.{VECTOR_DATE}.z00-z11.pmtiles",
    "base|14": f"openstreetmap-openmaptiles.{VECTOR_DATE}.z00-z14.pmtiles",
    "satellite|7": f"s2maps-sentinel2-2023.{SLOW_DATE}.z00-z07.pmtiles",
    "satellite|9": f"s2maps-sentinel2-2023.{SLOW_DATE}.z00-z09.pmtiles",
    "satellite|11": f"s2maps-sentinel2-2023.{SLOW_DATE}.z00-z11.pmtiles",
    "satellite|13": f"s2maps-sentinel2-2023.{SLOW_DATE}.z00-z13.pmtiles",
    "terrain|7": f"terrarium.{SLOW_DATE}.z00-z07.pmtiles",
    "terrain|8": f"terrarium.{SLOW_DATE}.z00-z08.pmtiles",
    "terrain|9": f"terrarium.{SLOW_DATE}.z00-z09.pmtiles",
    "terrain|10": f"terrarium.{SLOW_DATE}.z00-z10.pmtiles",
    "search|pop-1k-cities": f"static-search.{SEARCH_DATE}.pop-1k-cities.tar.gz",
}

SIZE_RE = re.compile(r"<size>(\d+)</size>")
CSV_PATH = os.path.join("src", "main", "assets", "maps_catalog.csv")


def fetch_size(fname):
    """The <size> from a layer's .meta4, or None on any failure (kept non-fatal)."""
    url = f"{BASE}{fname}.meta4"
    try:
        req = urllib.request.Request(url, headers={"User-Agent": UA})
        with urllib.request.urlopen(req, timeout=8) as resp:
            if resp.status != 200:
                sys.stderr.write(f">> [maps catalog] HTTP {resp.status} for {url}\n")
                return None
            body = resp.read().decode("utf-8", "replace")
    except Exception as e:
        sys.stderr.write(f">> [maps catalog] fetch failed for {url}: {e}\n")
        return None
    m = SIZE_RE.search(body)
    if not m:
        sys.stderr.write(f">> [maps catalog] no <size> element in {url}\n")
        return None
    return m.group(1)


def main():
    sizes = {}
    for key, fname in FILES.items():
        s = fetch_size(fname)
        if s is not None:
            sizes[key] = s
    if len(sizes) != len(FILES):
        # Partial fetch -> keep the committed CSV, exactly like the old task did.
        sys.stderr.write(
            f">> [maps catalog] incomplete fetch ({len(sizes)}/{len(FILES)}); "
            f"kept existing {CSV_PATH} (last known).\n")
        return 0
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    rows = []
    for key, fname in FILES.items():
        group, level = key.split("|", 1)
        rows.append(f"{group},{level},{fname},{sizes[key]},{today}")
    os.makedirs(os.path.dirname(CSV_PATH), exist_ok=True)
    with open(CSV_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("# group,level,file,bytes,fetched_date -- AUTO-GENERATED by "
                "tools/build_maps_catalog.py; do not edit by hand\n")
        f.write("# Whole-world pmtiles from https://iiab.switnet.org/maps/2 "
                "(roles/maps/defaults dates). The app sends 'file' as the download "
                "id; the box composes the URL.\n")
        f.write("\n".join(rows) + "\n")
    print(f">> [maps catalog] updated {len(rows)} entries in {CSV_PATH} ({today}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
