- name: Assert that "code_addons_install is sameas true" (boolean not string etc)
  assert:
    that: code_addons_install is sameas true
    fail_msg: "PLEASE SET 'code_addons_install: True' e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that "code_addons_enabled | type_debug == 'bool'" (boolean not string etc)
  assert:
    that: code_addons_enabled | type_debug == 'bool'
    fail_msg: "PLEASE GIVE VARIABLE 'code_addons_enabled' A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes


- block:

    - name: Install the add-ons gallery if 'code_addons_installed' not defined, e.g. in {{ iiab_state_file }}
      include_tasks: install.yml
      when: code_addons_installed is undefined

    - name: Enable/Disable/Reload NGINX for the add-ons gallery
      include_tasks: enable-or-disable.yml

    - name: Add 'code_addons' variable values to {{ iiab_ini_file }}
      ini_file:
        path: "{{ iiab_ini_file }}"    # /etc/iiab/iiab.ini
        section: code_addons
        option: "{{ item.option }}"
        value: "{{ item.value | string }}"
      with_items:
        - option: name
          value: Code on the Go Add-ons
        - option: description
          value: 'Offline gallery of Code on the Go add-ons.'
        - option: code_addons_install
          value: "{{ code_addons_install }}"
        - option: code_addons_enabled
          value: "{{ code_addons_enabled }}"
        - option: code_addons_url
          value: "{{ code_addons_url }}"

  rescue:

    - name: 'SEE ERROR ABOVE (skip_role_on_error: {{ skip_role_on_error }})'
      fail:
        msg: ""
      when: not skip_role_on_error
